package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhServicesFacilities<M extends BaseYhServicesFacilities<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setHid(java.lang.Long hid) {
		set("hid", hid);
	}

	public java.lang.Long getHid() {
		return get("hid");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setCODE(java.lang.String CODE) {
		set("CODE", CODE);
	}

	public java.lang.String getCODE() {
		return get("CODE");
	}

	public void setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
	}

	public java.lang.Integer getTYPE() {
		return get("TYPE");
	}

	public void setHacid(java.lang.String hacid) {
		set("hacid", hacid);
	}

	public java.lang.String getHacid() {
		return get("hacid");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setServiceId(java.lang.Long serviceId) {
		set("service_id", serviceId);
	}

	public java.lang.Long getServiceId() {
		return get("service_id");
	}

	public void setSupHid(java.lang.Long supHid) {
		set("sup_hid", supHid);
	}

	public java.lang.Long getSupHid() {
		return get("sup_hid");
	}

}
