package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhCity<M extends BaseYhCity<M>> extends Model<M> implements IBean {

	public void setCityid(java.lang.Long cityid) {
		set("cityid", cityid);
	}

	public java.lang.Long getCityid() {
		return get("cityid");
	}

	public void setStateid(java.lang.Long stateid) {
		set("stateid", stateid);
	}

	public java.lang.Long getStateid() {
		return get("stateid");
	}

	public void setStatecd(java.lang.String statecd) {
		set("statecd", statecd);
	}

	public java.lang.String getStatecd() {
		return get("statecd");
	}

	public void setCitycd(java.lang.String citycd) {
		set("citycd", citycd);
	}

	public java.lang.String getCitycd() {
		return get("citycd");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCitypin(java.lang.String citypin) {
		set("citypin", citypin);
	}

	public java.lang.String getCitypin() {
		return get("citypin");
	}

	public void setCitypinyinsimp(java.lang.String citypinyinsimp) {
		set("citypinyinsimp", citypinyinsimp);
	}

	public java.lang.String getCitypinyinsimp() {
		return get("citypinyinsimp");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
