package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhTravelDay<M extends BaseYhTravelDay<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTId(java.lang.Long tId) {
		set("t_id", tId);
	}

	public java.lang.Long getTId() {
		return get("t_id");
	}

	public void setTNo(java.lang.String tNo) {
		set("t_no", tNo);
	}

	public java.lang.String getTNo() {
		return get("t_no");
	}

	public void setTdNo(java.lang.String tdNo) {
		set("td_no", tdNo);
	}

	public java.lang.String getTdNo() {
		return get("td_no");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setTicketCount(java.lang.Integer ticketCount) {
		set("ticket_count", ticketCount);
	}

	public java.lang.Integer getTicketCount() {
		return get("ticket_count");
	}

	public void setTicketMinHour(java.lang.Integer ticketMinHour) {
		set("ticket_min_hour", ticketMinHour);
	}

	public java.lang.Integer getTicketMinHour() {
		return get("ticket_min_hour");
	}

	public void setTicketMaxHour(java.lang.Integer ticketMaxHour) {
		set("ticket_max_hour", ticketMaxHour);
	}

	public java.lang.Integer getTicketMaxHour() {
		return get("ticket_max_hour");
	}

	public void setRestCount(java.lang.Integer restCount) {
		set("rest_count", restCount);
	}

	public java.lang.Integer getRestCount() {
		return get("rest_count");
	}

	public void setRestMinHour(java.lang.Integer restMinHour) {
		set("rest_min_hour", restMinHour);
	}

	public java.lang.Integer getRestMinHour() {
		return get("rest_min_hour");
	}

	public void setRestMaxHour(java.lang.Integer restMaxHour) {
		set("rest_max_hour", restMaxHour);
	}

	public java.lang.Integer getRestMaxHour() {
		return get("rest_max_hour");
	}

	public void setPlayDate(java.util.Date playDate) {
		set("play_date", playDate);
	}

	public java.util.Date getPlayDate() {
		return get("play_date");
	}

	public void setPlayCityId(java.lang.Long playCityId) {
		set("play_city_id", playCityId);
	}

	public java.lang.Long getPlayCityId() {
		return get("play_city_id");
	}

	public void setPlayCityName(java.lang.String playCityName) {
		set("play_city_name", playCityName);
	}

	public java.lang.String getPlayCityName() {
		return get("play_city_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
