package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhProductDistance<M extends BaseYhProductDistance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOriginPid(java.lang.Long originPid) {
		set("origin_pid", originPid);
	}

	public java.lang.Long getOriginPid() {
		return get("origin_pid");
	}

	public void setDestinPid(java.lang.Long destinPid) {
		set("destin_pid", destinPid);
	}

	public java.lang.Long getDestinPid() {
		return get("destin_pid");
	}

	public void setDistance(java.lang.Long distance) {
		set("distance", distance);
	}

	public java.lang.Long getDistance() {
		return get("distance");
	}

	public void setOriginDestin(java.lang.Long originDestin) {
		set("origin_destin", originDestin);
	}

	public java.lang.Long getOriginDestin() {
		return get("origin_destin");
	}

}
