package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupRoomPrice<M extends BaseSupRoomPrice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setHotelId(java.lang.String hotelId) {
		set("hotel_id", hotelId);
	}

	public java.lang.String getHotelId() {
		return get("hotel_id");
	}

	public void setNameCn(java.lang.String nameCn) {
		set("name_cn", nameCn);
	}

	public java.lang.String getNameCn() {
		return get("name_cn");
	}

	public void setRoomTypeId(java.lang.String roomTypeId) {
		set("room_type_id", roomTypeId);
	}

	public java.lang.String getRoomTypeId() {
		return get("room_type_id");
	}

	public void setRoomTypeName(java.lang.String roomTypeName) {
		set("room_type_name", roomTypeName);
	}

	public java.lang.String getRoomTypeName() {
		return get("room_type_name");
	}

	public void setPricingType(java.lang.String pricingType) {
		set("pricing_type", pricingType);
	}

	public java.lang.String getPricingType() {
		return get("pricing_type");
	}

	public void setNight(java.util.Date night) {
		set("night", night);
	}

	public java.util.Date getNight() {
		return get("night");
	}

	public void setSupplierId(java.lang.Long supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Long getSupplierId() {
		return get("supplier_id");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public void setFacepayType(java.lang.String facepayType) {
		set("facepay_type", facepayType);
	}

	public java.lang.String getFacepayType() {
		return get("facepay_type");
	}

	public void setPreePrice(java.lang.Float preePrice) {
		set("pree_price", preePrice);
	}

	public java.lang.Float getPreePrice() {
		return get("pree_price");
	}

	public void setFacePrice(java.lang.Float facePrice) {
		set("face_price", facePrice);
	}

	public java.lang.Float getFacePrice() {
		return get("face_price");
	}

	public void setRateType(java.lang.Integer rateType) {
		set("rate_type", rateType);
	}

	public java.lang.Integer getRateType() {
		return get("rate_type");
	}

	public void setRateTypeName(java.lang.String rateTypeName) {
		set("rate_type_name", rateTypeName);
	}

	public java.lang.String getRateTypeName() {
		return get("rate_type_name");
	}

	public void setIncludeBreakfastQty2(java.lang.String includeBreakfastQty2) {
		set("include_breakfast_qty2", includeBreakfastQty2);
	}

	public java.lang.String getIncludeBreakfastQty2() {
		return get("include_breakfast_qty2");
	}

	public void setQtyable(java.lang.Integer qtyable) {
		set("qtyable", qtyable);
	}

	public java.lang.Integer getQtyable() {
		return get("qtyable");
	}

	public void setInterneTprice(java.lang.String interneTprice) {
		set("interne_tprice", interneTprice);
	}

	public java.lang.String getInterneTprice() {
		return get("interne_tprice");
	}

	public void setNetCharge(java.lang.Float netCharge) {
		set("net_charge", netCharge);
	}

	public java.lang.Float getNetCharge() {
		return get("net_charge");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setTermType(java.lang.String termType) {
		set("term_type", termType);
	}

	public java.lang.String getTermType() {
		return get("term_type");
	}

	public void setAdvanceDays(java.lang.Integer advanceDays) {
		set("advance_days", advanceDays);
	}

	public java.lang.Integer getAdvanceDays() {
		return get("advance_days");
	}

	public void setAdvanceTime(java.lang.String advanceTime) {
		set("advance_time", advanceTime);
	}

	public java.lang.String getAdvanceTime() {
		return get("advance_time");
	}

	public void setAppointedDate(java.util.Date appointedDate) {
		set("appointed_date", appointedDate);
	}

	public java.util.Date getAppointedDate() {
		return get("appointed_date");
	}

	public void setContinuousDays(java.lang.Integer continuousDays) {
		set("continuous_days", continuousDays);
	}

	public java.lang.Integer getContinuousDays() {
		return get("continuous_days");
	}

	public void setBeginday(java.util.Date beginday) {
		set("beginday", beginday);
	}

	public java.util.Date getBeginday() {
		return get("beginday");
	}

	public void setEndday(java.util.Date endday) {
		set("endday", endday);
	}

	public java.util.Date getEndday() {
		return get("endday");
	}

	public void setVoidabletype(java.lang.String voidabletype) {
		set("voidabletype", voidabletype);
	}

	public java.lang.String getVoidabletype() {
		return get("voidabletype");
	}

	public void setCashscaleType(java.lang.String cashscaleType) {
		set("cashscale_type", cashscaleType);
	}

	public java.lang.String getCashscaleType() {
		return get("cashscale_type");
	}

	public void setAdvancedays2(java.lang.String advancedays2) {
		set("advancedays2", advancedays2);
	}

	public java.lang.String getAdvancedays2() {
		return get("advancedays2");
	}

	public void setBeginday2(java.util.Date beginday2) {
		set("beginday2", beginday2);
	}

	public java.util.Date getBeginday2() {
		return get("beginday2");
	}

	public void setEndday2(java.util.Date endday2) {
		set("endday2", endday2);
	}

	public java.util.Date getEndday2() {
		return get("endday2");
	}

	public void setAdvanceTime2(java.lang.String advanceTime2) {
		set("advance_time2", advanceTime2);
	}

	public java.lang.String getAdvanceTime2() {
		return get("advance_time2");
	}

	public void setResType(java.lang.String resType) {
		set("res_type", resType);
	}

	public java.lang.String getResType() {
		return get("res_type");
	}

	public void setDaySelect(java.lang.String daySelect) {
		set("day_select", daySelect);
	}

	public java.lang.String getDaySelect() {
		return get("day_select");
	}

	public void setTimeSelect(java.lang.String timeSelect) {
		set("time_select", timeSelect);
	}

	public java.lang.String getTimeSelect() {
		return get("time_select");
	}

	public void setNoeditOrcancel(java.lang.String noeditOrcancel) {
		set("noedit_orcancel", noeditOrcancel);
	}

	public java.lang.String getNoeditOrcancel() {
		return get("noedit_orcancel");
	}

	public void setNoedit(java.lang.String noedit) {
		set("noedit", noedit);
	}

	public java.lang.String getNoedit() {
		return get("noedit");
	}

	public void setKeyId(java.lang.String keyId) {
		set("key_id", keyId);
	}

	public java.lang.String getKeyId() {
		return get("key_id");
	}

	public void setIsHousing(java.lang.String isHousing) {
		set("is_housing", isHousing);
	}

	public java.lang.String getIsHousing() {
		return get("is_housing");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
