package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhHotelsOrder<M extends BaseYhHotelsOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public void setOid(java.lang.Long oid) {
		set("oid", oid);
	}

	public java.lang.Long getOid() {
		return get("oid");
	}

	public void setHid(java.lang.Long hid) {
		set("hid", hid);
	}

	public java.lang.Long getHid() {
		return get("hid");
	}

	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}

	public java.lang.Long getPid() {
		return get("pid");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setZname(java.lang.String zname) {
		set("zname", zname);
	}

	public java.lang.String getZname() {
		return get("zname");
	}

	public void setEname(java.lang.String ename) {
		set("ename", ename);
	}

	public java.lang.String getEname() {
		return get("ename");
	}

	public void setRoomType(java.lang.Integer roomType) {
		set("room_type", roomType);
	}

	public java.lang.Integer getRoomType() {
		return get("room_type");
	}

	public void setBreakfast(java.lang.Integer breakfast) {
		set("breakfast", breakfast);
	}

	public java.lang.Integer getBreakfast() {
		return get("breakfast");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setCountryId(java.lang.Long countryId) {
		set("country_id", countryId);
	}

	public java.lang.Long getCountryId() {
		return get("country_id");
	}

	public void setCountryName(java.lang.String countryName) {
		set("country_name", countryName);
	}

	public java.lang.String getCountryName() {
		return get("country_name");
	}

	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public void setProvinceId(java.lang.Long provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Long getProvinceId() {
		return get("province_id");
	}

	public void setCityCode(java.lang.Long cityCode) {
		set("city_code", cityCode);
	}

	public java.lang.Long getCityCode() {
		return get("city_code");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}

	public java.lang.String getAreaName() {
		return get("area_name");
	}

	public void setHotelStarRate(java.lang.Integer hotelStarRate) {
		set("hotel_star_rate", hotelStarRate);
	}

	public java.lang.Integer getHotelStarRate() {
		return get("hotel_star_rate");
	}

	public void setCtripStarRate(java.lang.String ctripStarRate) {
		set("ctrip_star_rate", ctripStarRate);
	}

	public java.lang.String getCtripStarRate() {
		return get("ctrip_star_rate");
	}

	public void setCtripRecommendRate(java.lang.String ctripRecommendRate) {
		set("ctrip_recommend_rate", ctripRecommendRate);
	}

	public java.lang.String getCtripRecommendRate() {
		return get("ctrip_recommend_rate");
	}

	public void setPlatitude(java.lang.String platitude) {
		set("platitude", platitude);
	}

	public java.lang.String getPlatitude() {
		return get("platitude");
	}

	public void setPlongitude(java.lang.String plongitude) {
		set("plongitude", plongitude);
	}

	public java.lang.String getPlongitude() {
		return get("plongitude");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setSname(java.lang.String sname) {
		set("sname", sname);
	}

	public java.lang.String getSname() {
		return get("sname");
	}

	public void setSid(java.lang.Long sid) {
		set("sid", sid);
	}

	public java.lang.Long getSid() {
		return get("sid");
	}

	public void setScode(java.lang.String scode) {
		set("scode", scode);
	}

	public java.lang.String getScode() {
		return get("scode");
	}

	public void setIsCancel(java.lang.Integer isCancel) {
		set("is_cancel", isCancel);
	}

	public java.lang.Integer getIsCancel() {
		return get("is_cancel");
	}

	public void setCancelStartTime(java.util.Date cancelStartTime) {
		set("cancel_start_time", cancelStartTime);
	}

	public java.util.Date getCancelStartTime() {
		return get("cancel_start_time");
	}

	public void setCancelEndTime(java.util.Date cancelEndTime) {
		set("cancel_end_time", cancelEndTime);
	}

	public java.util.Date getCancelEndTime() {
		return get("cancel_end_time");
	}

	public void setCancelAmount(java.lang.Double cancelAmount) {
		set("cancel_amount", cancelAmount);
	}

	public java.lang.Double getCancelAmount() {
		return get("cancel_amount");
	}

	public void setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
	}

	public java.lang.Integer getPaymentStatus() {
		return get("payment_status");
	}

	public void setPaymentType(java.lang.Integer paymentType) {
		set("payment_type", paymentType);
	}

	public java.lang.Integer getPaymentType() {
		return get("payment_type");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
