package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhBizzone<M extends BaseYhBizzone<M>> extends Model<M> implements IBean {

	public void setBizzoneid(java.lang.Long bizzoneid) {
		set("bizzoneid", bizzoneid);
	}

	public java.lang.Long getBizzoneid() {
		return get("bizzoneid");
	}

	public void setCityid(java.lang.Long cityid) {
		set("cityid", cityid);
	}

	public java.lang.Long getCityid() {
		return get("cityid");
	}

	public void setCitycd(java.lang.String citycd) {
		set("citycd", citycd);
	}

	public java.lang.String getCitycd() {
		return get("citycd");
	}

	public void setZoneid(java.lang.Long zoneid) {
		set("zoneid", zoneid);
	}

	public java.lang.Long getZoneid() {
		return get("zoneid");
	}

	public void setZonename(java.lang.String zonename) {
		set("zonename", zonename);
	}

	public java.lang.String getZonename() {
		return get("zonename");
	}

	public void setZonecd(java.lang.String zonecd) {
		set("zonecd", zonecd);
	}

	public java.lang.String getZonecd() {
		return get("zonecd");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
