package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhOrder<M extends BaseYhOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public void setAmount(java.lang.Double amount) {
		set("amount", amount);
	}

	public java.lang.Double getAmount() {
		return get("amount");
	}

	public void setCurrencyCode(java.lang.String currencyCode) {
		set("currency_code", currencyCode);
	}

	public java.lang.String getCurrencyCode() {
		return get("currency_code");
	}

	public void setPaymentType(java.lang.Integer paymentType) {
		set("payment_type", paymentType);
	}

	public java.lang.Integer getPaymentType() {
		return get("payment_type");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setTravelId(java.lang.Long travelId) {
		set("travel_id", travelId);
	}

	public java.lang.Long getTravelId() {
		return get("travel_id");
	}

	public void setTravelNo(java.lang.String travelNo) {
		set("travel_no", travelNo);
	}

	public java.lang.String getTravelNo() {
		return get("travel_no");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setOrderCo(java.lang.String orderCo) {
		set("order_co", orderCo);
	}

	public java.lang.String getOrderCo() {
		return get("order_co");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
	}

	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setRefundTime(java.util.Date refundTime) {
		set("refund_time", refundTime);
	}

	public java.util.Date getRefundTime() {
		return get("refund_time");
	}

}
