package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhSeasonTravel<M extends BaseYhSeasonTravel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSketch(java.lang.String sketch) {
		set("sketch", sketch);
	}

	public java.lang.String getSketch() {
		return get("sketch");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setYhPrice(java.lang.Double yhPrice) {
		set("yh_price", yhPrice);
	}

	public java.lang.Double getYhPrice() {
		return get("yh_price");
	}

	public void setMarketPrice(java.lang.Double marketPrice) {
		set("market_price", marketPrice);
	}

	public java.lang.Double getMarketPrice() {
		return get("market_price");
	}

	public void setRecommendReason(java.lang.String recommendReason) {
		set("recommend_reason", recommendReason);
	}

	public java.lang.String getRecommendReason() {
		return get("recommend_reason");
	}

	public void setProductContent(java.lang.String productContent) {
		set("product_content", productContent);
	}

	public java.lang.String getProductContent() {
		return get("product_content");
	}

	public void setCostDescription(java.lang.String costDescription) {
		set("cost_description", costDescription);
	}

	public java.lang.String getCostDescription() {
		return get("cost_description");
	}

	public void setBookingNotice(java.lang.String bookingNotice) {
		set("booking_notice", bookingNotice);
	}

	public java.lang.String getBookingNotice() {
		return get("booking_notice");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
