package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhJourney<M extends BaseYhJourney<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBeginType(java.lang.Long beginType) {
		set("begin_type", beginType);
	}

	public java.lang.Long getBeginType() {
		return get("begin_type");
	}

	public void setEndType(java.lang.Long endType) {
		set("end_type", endType);
	}

	public java.lang.Long getEndType() {
		return get("end_type");
	}

	public void setBeginId(java.lang.String beginId) {
		set("begin_id", beginId);
	}

	public java.lang.String getBeginId() {
		return get("begin_id");
	}

	public void setEndId(java.lang.String endId) {
		set("end_id", endId);
	}

	public java.lang.String getEndId() {
		return get("end_id");
	}

	public void setBeginJingdu(java.lang.String beginJingdu) {
		set("begin_jingdu", beginJingdu);
	}

	public java.lang.String getBeginJingdu() {
		return get("begin_jingdu");
	}

	public void setBeginWeidu(java.util.Date beginWeidu) {
		set("begin_weidu", beginWeidu);
	}

	public java.util.Date getBeginWeidu() {
		return get("begin_weidu");
	}

	public void setEndJingdu(java.util.Date endJingdu) {
		set("end_jingdu", endJingdu);
	}

	public java.util.Date getEndJingdu() {
		return get("end_jingdu");
	}

	public void setEndWeidu(java.lang.String endWeidu) {
		set("end_weidu", endWeidu);
	}

	public java.lang.String getEndWeidu() {
		return get("end_weidu");
	}

	public void setMeter(java.lang.String meter) {
		set("meter", meter);
	}

	public java.lang.String getMeter() {
		return get("meter");
	}

	public void setDurationCar(java.lang.Integer durationCar) {
		set("duration_car", durationCar);
	}

	public java.lang.Integer getDurationCar() {
		return get("duration_car");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
