package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysThirdParty<M extends BaseSysThirdParty<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSysId(java.lang.Long sysId) {
		set("sys_id", sysId);
	}

	public java.lang.Long getSysId() {
		return get("sys_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setTpType(java.lang.Integer tpType) {
		set("tp_type", tpType);
	}

	public java.lang.Integer getTpType() {
		return get("tp_type");
	}

	public void setUsercode(java.lang.String usercode) {
		set("usercode", usercode);
	}

	public java.lang.String getUsercode() {
		return get("usercode");
	}

	public void setTpCode(java.lang.String tpCode) {
		set("tp_code", tpCode);
	}

	public java.lang.String getTpCode() {
		return get("tp_code");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
