package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhSupCity<M extends BaseYhSupCity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSupId(java.lang.Long supId) {
		set("sup_id", supId);
	}

	public java.lang.Long getSupId() {
		return get("sup_id");
	}

	public void setYhCityId(java.lang.Long yhCityId) {
		set("yh_city_id", yhCityId);
	}

	public java.lang.Long getYhCityId() {
		return get("yh_city_id");
	}

	public void setSupCityId(java.lang.String supCityId) {
		set("sup_city_id", supCityId);
	}

	public java.lang.String getSupCityId() {
		return get("sup_city_id");
	}

	public void setSupStateId(java.lang.String supStateId) {
		set("sup_state_id", supStateId);
	}

	public java.lang.String getSupStateId() {
		return get("sup_state_id");
	}

	public void setSupCountryId(java.lang.String supCountryId) {
		set("sup_country_id", supCountryId);
	}

	public java.lang.String getSupCountryId() {
		return get("sup_country_id");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
