package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMember<M extends BaseSysMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUsercode(java.lang.String usercode) {
		set("usercode", usercode);
	}

	public java.lang.String getUsercode() {
		return get("usercode");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setGender(java.lang.Boolean gender) {
		set("gender", gender);
	}

	public java.lang.Boolean getGender() {
		return get("gender");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setLocked(java.lang.Integer locked) {
		set("locked", locked);
	}

	public java.lang.Integer getLocked() {
		return get("locked");
	}

	public void setDegree(java.lang.Integer degree) {
		set("degree", degree);
	}

	public java.lang.Integer getDegree() {
		return get("degree");
	}

	public void setHeadPortrait(java.lang.String headPortrait) {
		set("head_portrait", headPortrait);
	}

	public java.lang.String getHeadPortrait() {
		return get("head_portrait");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setIntegral(java.lang.String integral) {
		set("integral", integral);
	}

	public java.lang.String getIntegral() {
		return get("integral");
	}

	public void setWeixin(java.lang.String weixin) {
		set("weixin", weixin);
	}

	public java.lang.String getWeixin() {
		return get("weixin");
	}

	public void setWeibo(java.lang.String weibo) {
		set("weibo", weibo);
	}

	public java.lang.String getWeibo() {
		return get("weibo");
	}

	public void setIsCheckPhone(java.lang.Integer isCheckPhone) {
		set("is_check_phone", isCheckPhone);
	}

	public java.lang.Integer getIsCheckPhone() {
		return get("is_check_phone");
	}

	public void setIsCheckEmail(java.lang.Integer isCheckEmail) {
		set("is_check_email", isCheckEmail);
	}

	public java.lang.Integer getIsCheckEmail() {
		return get("is_check_email");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setHimage(java.lang.String himage) {
		set("himage", himage);
	}

	public java.lang.String getHimage() {
		return get("himage");
	}

}
