package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhTravelDetail<M extends BaseYhTravelDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTId(java.lang.Long tId) {
		set("t_id", tId);
	}

	public java.lang.Long getTId() {
		return get("t_id");
	}

	public void setTNo(java.lang.String tNo) {
		set("t_no", tNo);
	}

	public java.lang.String getTNo() {
		return get("t_no");
	}

	public void setTdId(java.lang.Long tdId) {
		set("td_id", tdId);
	}

	public java.lang.Long getTdId() {
		return get("td_id");
	}

	public void setTdNo(java.lang.String tdNo) {
		set("td_no", tdNo);
	}

	public java.lang.String getTdNo() {
		return get("td_no");
	}

	public void setDNo(java.lang.String dNo) {
		set("d_no", dNo);
	}

	public java.lang.String getDNo() {
		return get("d_no");
	}

	public void setPtype(java.lang.Integer ptype) {
		set("ptype", ptype);
	}

	public java.lang.Integer getPtype() {
		return get("ptype");
	}

	public void setPname(java.lang.String pname) {
		set("pname", pname);
	}

	public java.lang.String getPname() {
		return get("pname");
	}

	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}

	public java.lang.Long getPid() {
		return get("pid");
	}

	public void setImageKey(java.lang.String imageKey) {
		set("image_key", imageKey);
	}

	public java.lang.String getImageKey() {
		return get("image_key");
	}

	public void setPlayTime(java.lang.String playTime) {
		set("play_time", playTime);
	}

	public java.lang.String getPlayTime() {
		return get("play_time");
	}

	public void setProductLabel(java.lang.String productLabel) {
		set("product_label", productLabel);
	}

	public java.lang.String getProductLabel() {
		return get("product_label");
	}

	public void setPlongitude(java.lang.String plongitude) {
		set("plongitude", plongitude);
	}

	public java.lang.String getPlongitude() {
		return get("plongitude");
	}

	public void setPlatitude(java.lang.String platitude) {
		set("platitude", platitude);
	}

	public java.lang.String getPlatitude() {
		return get("platitude");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setStartPlay(java.lang.String startPlay) {
		set("start_play", startPlay);
	}

	public java.lang.String getStartPlay() {
		return get("start_play");
	}

}
