package com.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYhRestaurant<M extends BaseYhRestaurant<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setCountryId(java.lang.Long countryId) {
		set("country_id", countryId);
	}

	public java.lang.Long getCountryId() {
		return get("country_id");
	}

	public void setCountryName(java.lang.String countryName) {
		set("country_name", countryName);
	}

	public java.lang.String getCountryName() {
		return get("country_name");
	}

	public void setCityCode(java.lang.Long cityCode) {
		set("city_code", cityCode);
	}

	public java.lang.Long getCityCode() {
		return get("city_code");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}

	public java.lang.String getAreaName() {
		return get("area_name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setCreateId(java.lang.Long createId) {
		set("create_id", createId);
	}

	public java.lang.Long getCreateId() {
		return get("create_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateId(java.lang.Long updateId) {
		set("update_id", updateId);
	}

	public java.lang.Long getUpdateId() {
		return get("update_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setPlatitude(java.lang.String platitude) {
		set("platitude", platitude);
	}

	public java.lang.String getPlatitude() {
		return get("platitude");
	}

	public void setPlongitude(java.lang.String plongitude) {
		set("plongitude", plongitude);
	}

	public java.lang.String getPlongitude() {
		return get("plongitude");
	}

	public void setProvinceId(java.lang.Long provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Long getProvinceId() {
		return get("province_id");
	}

	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setAllName(java.lang.String allName) {
		set("all_name", allName);
	}

	public java.lang.String getAllName() {
		return get("all_name");
	}

	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}

	public java.lang.String getShortName() {
		return get("short_name");
	}

	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}

	public java.lang.Long getPid() {
		return get("pid");
	}

	public void setIncreaseRate(java.lang.String increaseRate) {
		set("increase_rate", increaseRate);
	}

	public java.lang.String getIncreaseRate() {
		return get("increase_rate");
	}

	public void setIncreaseMoney(java.lang.Double increaseMoney) {
		set("increase_money", increaseMoney);
	}

	public java.lang.Double getIncreaseMoney() {
		return get("increase_money");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setGraphic(java.lang.String graphic) {
		set("graphic", graphic);
	}

	public java.lang.String getGraphic() {
		return get("graphic");
	}

	public void setFitSeason(java.lang.String fitSeason) {
		set("fit_Season", fitSeason);
	}

	public java.lang.String getFitSeason() {
		return get("fit_Season");
	}

	public void setMinDuration(java.lang.Integer minDuration) {
		set("min_duration", minDuration);
	}

	public java.lang.Integer getMinDuration() {
		return get("min_duration");
	}

	public void setMaxDuration(java.lang.Integer maxDuration) {
		set("max_duration", maxDuration);
	}

	public java.lang.Integer getMaxDuration() {
		return get("max_duration");
	}

	public void setBd(java.lang.Long bd) {
		set("bd", bd);
	}

	public java.lang.Long getBd() {
		return get("bd");
	}

	public void setBdName(java.lang.String bdName) {
		set("bd_name", bdName);
	}

	public java.lang.String getBdName() {
		return get("bd_name");
	}

	public void setMaxNumber(java.lang.Integer maxNumber) {
		set("max_number", maxNumber);
	}

	public java.lang.Integer getMaxNumber() {
		return get("max_number");
	}

	public void setMinNumber(java.lang.Integer minNumber) {
		set("min_number", minNumber);
	}

	public java.lang.Integer getMinNumber() {
		return get("min_number");
	}

	public void setIningCene(java.lang.String iningCene) {
		set("ining_cene", iningCene);
	}

	public java.lang.String getIningCene() {
		return get("ining_cene");
	}

	public void setTaste(java.lang.String taste) {
		set("taste", taste);
	}

	public java.lang.String getTaste() {
		return get("taste");
	}

	public void setServe(java.lang.String serve) {
		set("serve", serve);
	}

	public java.lang.String getServe() {
		return get("serve");
	}

	public void setMtScore(java.lang.Double mtScore) {
		set("mt_score", mtScore);
	}

	public java.lang.Double getMtScore() {
		return get("mt_score");
	}

	public void setNmScore(java.lang.Double nmScore) {
		set("nm_score", nmScore);
	}

	public java.lang.Double getNmScore() {
		return get("nm_score");
	}

	public void setDzdpScore(java.lang.Double dzdpScore) {
		set("dzdp_score", dzdpScore);
	}

	public java.lang.Double getDzdpScore() {
		return get("dzdp_score");
	}

	public void setYhScore(java.lang.Double yhScore) {
		set("yh_score", yhScore);
	}

	public java.lang.Double getYhScore() {
		return get("yh_score");
	}

	public void setEatTime(java.lang.Double eatTime) {
		set("eat_time", eatTime);
	}

	public java.lang.Double getEatTime() {
		return get("eat_time");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}

	public java.lang.String getTips() {
		return get("tips");
	}

}
