package com.abc.model;

import com.abc.model.base.BaseSupHotels;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupHotels extends BaseSupHotels<SupHotels> {
	public static final SupHotels dao = new SupHotels();
}
