package com.abc.model;

import com.abc.model.base.BaseSupJiaChuang;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupJiaChuang extends BaseSupJiaChuang<SupJiaChuang> {
	public static final SupJiaChuang dao = new SupJiaChuang();
}
