package com.abc.model;

import com.abc.model.base.BaseSupJiaZao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupJiaZao extends BaseSupJiaZao<SupJiaZao> {
	public static final SupJiaZao dao = new SupJiaZao();
}
