package com.abc.model;

import com.abc.model.base.BaseSupRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupRoom extends BaseSupRoom<SupRoom> {
	public static final SupRoom dao = new SupRoom();
}
