package com.abc.model;

import com.abc.model.base.BaseSupRestaurant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupRestaurant extends BaseSupRestaurant<SupRestaurant> {
	public static final SupRestaurant dao = new SupRestaurant();
}
