package com.abc.model;

import com.abc.model.base.BaseSupRoomPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupRoomPrice extends BaseSupRoomPrice<SupRoomPrice> {
	public static final SupRoomPrice dao = new SupRoomPrice();
}
