package com.abc.model;

import com.abc.model.base.BaseSupTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupTicket extends BaseSupTicket<SupTicket> {
	public static final SupTicket dao = new SupTicket();
}
