package com.abc.model;

import com.abc.model.base.BaseSysAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAddress extends BaseSysAddress<SysAddress> {
	public static final SysAddress dao = new SysAddress();
}
