package com.abc.model;

import com.abc.model.base.BaseSysDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDepartment extends BaseSysDepartment<SysDepartment> {
	public static final SysDepartment dao = new SysDepartment();
}
