package com.abc.model;

import com.abc.model.base.BaseSysPersons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPersons extends BaseSysPersons<SysPersons> {
	public static final SysPersons dao = new SysPersons();
}
