package com.abc.model;

import com.abc.model.base.BaseSysPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPermission extends BaseSysPermission<SysPermission> {
	public static final SysPermission dao = new SysPermission();
}
