package com.abc.model;

import com.abc.model.base.BaseSysRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRolePermission extends BaseSysRolePermission<SysRolePermission> {
	public static final SysRolePermission dao = new SysRolePermission();
}
