package com.abc.model;

import com.abc.model.base.BaseSysStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysStation extends BaseSysStation<SysStation> {
	public static final SysStation dao = new SysStation();
}
