package com.abc.model;

import com.abc.model.base.BaseSysThirdParty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysThirdParty extends BaseSysThirdParty<SysThirdParty> {
	public static final SysThirdParty dao = new SysThirdParty();
}
