package com.abc.model;

import com.abc.model.base.BaseYhBizzone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhBizzone extends BaseYhBizzone<YhBizzone> {
	public static final YhBizzone dao = new YhBizzone();
}
