package com.abc.model;

import com.abc.model.base.BaseYhCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhCity extends BaseYhCity<YhCity> {
	public static final YhCity dao = new YhCity();
}
