package com.abc.model;

import com.abc.model.base.BaseYhCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhCountry extends BaseYhCountry<YhCountry> {
	public static final YhCountry dao = new YhCountry();
}
