package com.abc.model;

import com.abc.model.base.BaseYhDataDic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhDataDic extends BaseYhDataDic<YhDataDic> {
	public static final YhDataDic dao = new YhDataDic();
}
