package com.abc.model;

import com.abc.model.base.BaseYhHotels;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhHotels extends BaseYhHotels<YhHotels> {
	public static final YhHotels dao = new YhHotels();
}
