package com.abc.model;

import com.abc.model.base.BaseYhHotelsOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhHotelsOrder extends BaseYhHotelsOrder<YhHotelsOrder> {
	public static final YhHotelsOrder dao = new YhHotelsOrder();
}
