package com.abc.model;

import com.abc.model.base.BaseYhImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhImages extends BaseYhImages<YhImages> {
	public static final YhImages dao = new YhImages();
}
