package com.abc.model;

import com.abc.model.base.BaseYhJourney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhJourney extends BaseYhJourney<YhJourney> {
	public static final YhJourney dao = new YhJourney();
}
