package com.abc.model;

import com.abc.model.base.BaseYhLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhLabel extends BaseYhLabel<YhLabel> {
	public static final YhLabel dao = new YhLabel();
}
