package com.abc.model;

import com.abc.model.base.BaseYhLabelCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhLabelCity extends BaseYhLabelCity<YhLabelCity> {
	public static final YhLabelCity dao = new YhLabelCity();
}
