package com.abc.model;

import com.abc.model.base.BaseYhOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhOrder extends BaseYhOrder<YhOrder> {
	public static final YhOrder dao = new YhOrder();
}
