package com.abc.model;

import com.abc.model.base.BaseYhOrderPassengers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhOrderPassengers extends BaseYhOrderPassengers<YhOrderPassengers> {
	public static final YhOrderPassengers dao = new YhOrderPassengers();
}
