package com.abc.model;

import com.abc.model.base.BaseYhPlaneOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhPlaneOrder extends BaseYhPlaneOrder<YhPlaneOrder> {
	public static final YhPlaneOrder dao = new YhPlaneOrder();
}
