package com.abc.model;

import com.abc.model.base.BaseYhPlayMonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhPlayMonth extends BaseYhPlayMonth<YhPlayMonth> {
	public static final YhPlayMonth dao = new YhPlayMonth();
}
