package com.abc.model;

import com.abc.model.base.BaseYhProductDistance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhProductDistance extends BaseYhProductDistance<YhProductDistance> {
	public static final YhProductDistance dao = new YhProductDistance();
}
