package com.abc.model;

import com.abc.model.base.BaseYhProductLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhProductLabel extends BaseYhProductLabel<YhProductLabel> {
	public static final YhProductLabel dao = new YhProductLabel();
}
