package com.abc.model;

import com.abc.model.base.BaseYhProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhProduct extends BaseYhProduct<YhProduct> {
	public static final YhProduct dao = new YhProduct();
}
