package com.abc.model;

import com.abc.model.base.BaseYhRestaurant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhRestaurant extends BaseYhRestaurant<YhRestaurant> {
	public static final YhRestaurant dao = new YhRestaurant();
}
