package com.abc.model;

import com.abc.model.base.BaseYhRestaurantOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhRestaurantOrder extends BaseYhRestaurantOrder<YhRestaurantOrder> {
	public static final YhRestaurantOrder dao = new YhRestaurantOrder();
}
