package com.abc.model;

import com.abc.model.base.BaseYhRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhRoom extends BaseYhRoom<YhRoom> {
	public static final YhRoom dao = new YhRoom();
}
