package com.abc.model;

import com.abc.model.base.BaseYhSeasonTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhSeasonTravel extends BaseYhSeasonTravel<YhSeasonTravel> {
	public static final YhSeasonTravel dao = new YhSeasonTravel();
}
