package com.abc.model;

import com.abc.model.base.BaseYhServicesFacilities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhServicesFacilities extends BaseYhServicesFacilities<YhServicesFacilities> {
	public static final YhServicesFacilities dao = new YhServicesFacilities();
}
