package com.abc.model;

import com.abc.model.base.BaseYhStroke;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhStroke extends BaseYhStroke<YhStroke> {
	public static final YhStroke dao = new YhStroke();
}
