package com.abc.model;

import com.abc.model.base.BaseYhState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhState extends BaseYhState<YhState> {
	public static final YhState dao = new YhState();
}
