package com.abc.model;

import com.abc.model.base.BaseYhSupCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhSupCity extends BaseYhSupCity<YhSupCity> {
	public static final YhSupCity dao = new YhSupCity();
}
