package com.abc.model;

import com.abc.model.base.BaseYhSupplier;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhSupplier extends BaseYhSupplier<YhSupplier> {
	public static final YhSupplier dao = new YhSupplier();
}
