package com.abc.model;

import com.abc.model.base.BaseYhTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhTicket extends BaseYhTicket<YhTicket> {
	public static final YhTicket dao = new YhTicket();
}
