package com.abc.model;

import com.abc.model.base.BaseYhTicketOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhTicketOrder extends BaseYhTicketOrder<YhTicketOrder> {
	public static final YhTicketOrder dao = new YhTicketOrder();
}
