package com.abc.model;

import com.abc.model.base.BaseYhTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhTravel extends BaseYhTravel<YhTravel> {
	public static final YhTravel dao = new YhTravel();
}
