package com.abc.model;

import com.abc.model.base.BaseYhTravelDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhTravelDetail extends BaseYhTravelDetail<YhTravelDetail> {
	public static final YhTravelDetail dao = new YhTravelDetail();
}
