package com.abc.model;

import com.abc.model.base.BaseYhTravelDay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhTravelDay extends BaseYhTravelDay<YhTravelDay> {
	public static final YhTravelDay dao = new YhTravelDay();
}
