package com.abc.model;

import com.abc.model.base.BaseYhUploadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhUploadLog extends BaseYhUploadLog<YhUploadLog> {
	public static final YhUploadLog dao = new YhUploadLog();
}
