package com.abc.model;

import com.abc.model.base.BaseYhZone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhZone extends BaseYhZone<YhZone> {
	public static final YhZone dao = new YhZone();
}
